services:
#  mongo:
#    env_file: ".env.local"
#    ports:
#      - "${MONGODB_PORT}:27017"
#    environment:
#      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
#      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
#      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  postgres:
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}

  frontend:
    ports:
      - "${FRONTEND_PORT}:3000"

#  webapi:
#    env_file: ".env.local"
#    ports:
#      - "${WEBAPI_PORT}:5000"
#    depends_on:
#      - postgres
